"""add parser entry and level fields

Revision ID: 05fd23e2528f
Revises: 20260709_0001
Create Date: 2026-07-14 16:50:42.094373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fd23e2528f'
down_revision: Union[str, Sequence[str], None] = '20260709_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('entry_instruction', sa.String(length=30), server_default='UNSPECIFIED', nullable=False))
    op.add_column('recommendations', sa.Column('entry_instruction_text', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('entry_price_source', sa.String(length=30), server_default='MESSAGE', nullable=False))
    op.add_column('recommendations', sa.Column('entry_price_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recommendations', sa.Column('support_level', sa.Numeric(), nullable=True))
    op.add_column('recommendations', sa.Column('trigger_level', sa.Numeric(), nullable=True))
    op.alter_column('recommendations', 'symbol',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               nullable=False)
    op.alter_column('recommendations', 'action',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'action',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('recommendations', 'symbol',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('recommendations', 'trigger_level')
    op.drop_column('recommendations', 'support_level')
    op.drop_column('recommendations', 'entry_price_timestamp')
    op.drop_column('recommendations', 'entry_price_source')
    op.drop_column('recommendations', 'entry_instruction_text')
    op.drop_column('recommendations', 'entry_instruction')
    # ### end Alembic commands ###
