"""create Recommendation

Revision ID: 09ebd257d651
Revises: c1450b4804ca
Create Date: 2026-07-06 20:43:58.165264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ebd257d651'
down_revision: Union[str, Sequence[str], None] = 'c1450b4804ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('entry_low', sa.Numeric(), nullable=True),
    sa.Column('entry_high', sa.Numeric(), nullable=True),
    sa.Column('stop_loss', sa.Numeric(), nullable=True),
    sa.Column('target1', sa.Numeric(), nullable=True),
    sa.Column('target2', sa.Numeric(), nullable=True),
    sa.Column('target3', sa.Numeric(), nullable=True),
    sa.Column('pattern', sa.String(length=100), nullable=True),
    sa.Column('risk', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
