"""add message uniqueness constraint

Revision ID: 6ae8bb1a9a9d
Revises: fb6efb8f39a7
Create Date: 2026-07-07 21:30:34.956863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae8bb1a9a9d'
down_revision: Union[str, Sequence[str], None] = 'fb6efb8f39a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_message_channel_external_id', 'messages', ['channel_id', 'external_message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_message_channel_external_id', 'messages', type_='unique')
    # ### end Alembic commands ###
