"""add new table normalized_messages

Revision ID: 74545cb742d6
Revises: c4d58d11b112
Create Date: 2026-07-08 13:13:50.095970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74545cb742d6'
down_revision: Union[str, Sequence[str], None] = 'c4d58d11b112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normalized_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('instrument_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('parser_status', sa.String(length=20), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', name='uq_normalized_message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normalized_messages')
    # ### end Alembic commands ###
