"""create Channel

Revision ID: 9152c12a5290
Revises: 09ebd257d651
Create Date: 2026-07-07 13:57:13.712732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9152c12a5290'
down_revision: Union[str, Sequence[str], None] = '09ebd257d651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_name'),
    sa.UniqueConstraint('external_channel_id')
    )
    op.add_column('messages', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('messages_source_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'channels', ['channel_id'], ['id'])
    op.drop_column('messages', 'source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_source_id_fkey'), 'messages', 'sources', ['source_id'], ['id'])
    op.drop_column('messages', 'channel_id')
    op.drop_table('channels')
    # ### end Alembic commands ###
