"""add unique constraint on recommendation message

Revision ID: c4d58d11b112
Revises: 6ae8bb1a9a9d
Create Date: 2026-07-07 22:34:02.130837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d58d11b112'
down_revision: Union[str, Sequence[str], None] = '6ae8bb1a9a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_recommendation_message', 'recommendations', ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recommendation_message', 'recommendations', type_='unique')
    # ### end Alembic commands ###
