"""add last message fields to channels

Revision ID: fb6efb8f39a7
Revises: 9152c12a5290
Create Date: 2026-07-07 20:50:27.096848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6efb8f39a7'
down_revision: Union[str, Sequence[str], None] = '9152c12a5290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('last_message_id', sa.BigInteger(), nullable=True))
    op.add_column('channels', sa.Column('last_message_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'last_message_date')
    op.drop_column('channels', 'last_message_id')
    # ### end Alembic commands ###
